// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usergroupmodelusage"
)

// UserGroupModelUsageUpdate is the builder for updating UserGroupModelUsage entities.
type UserGroupModelUsageUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupModelUsageMutation
}

// Where appends a list predicates to the UserGroupModelUsageUpdate builder.
func (_u *UserGroupModelUsageUpdate) Where(ps ...predicate.UserGroupModelUsage) *UserGroupModelUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupModelUsageUpdate) SetUpdatedAt(v time.Time) *UserGroupModelUsageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupModelUsageUpdate) SetDeletedAt(v time.Time) *UserGroupModelUsageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableDeletedAt(v *time.Time) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupModelUsageUpdate) ClearDeletedAt() *UserGroupModelUsageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupModelUsageUpdate) SetUserID(v int64) *UserGroupModelUsageUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableUserID(v *int64) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupModelUsageUpdate) AddUserID(v int64) *UserGroupModelUsageUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupModelUsageUpdate) SetGroupID(v int64) *UserGroupModelUsageUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableGroupID(v *int64) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupModelUsageUpdate) AddGroupID(v int64) *UserGroupModelUsageUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRuleKey sets the "rule_key" field.
func (_u *UserGroupModelUsageUpdate) SetRuleKey(v string) *UserGroupModelUsageUpdate {
	_u.mutation.SetRuleKey(v)
	return _u
}

// SetNillableRuleKey sets the "rule_key" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableRuleKey(v *string) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetRuleKey(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) SetDailyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableDailyUsageUsd(v *float64) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) AddDailyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableWeeklyUsageUsd(v *float64) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) AddWeeklyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableMonthlyUsageUsd(v *float64) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserGroupModelUsageUpdate) AddMonthlyUsageUsd(v float64) *UserGroupModelUsageUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserGroupModelUsageUpdate) SetDailyWindowStart(v time.Time) *UserGroupModelUsageUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableDailyWindowStart(v *time.Time) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserGroupModelUsageUpdate) ClearDailyWindowStart() *UserGroupModelUsageUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserGroupModelUsageUpdate) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserGroupModelUsageUpdate) ClearWeeklyWindowStart() *UserGroupModelUsageUpdate {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserGroupModelUsageUpdate) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdate) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupModelUsageUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserGroupModelUsageUpdate) ClearMonthlyWindowStart() *UserGroupModelUsageUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// Mutation returns the UserGroupModelUsageMutation object of the builder.
func (_u *UserGroupModelUsageUpdate) Mutation() *UserGroupModelUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGroupModelUsageUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupModelUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGroupModelUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupModelUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupModelUsageUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupmodelusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupmodelusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupmodelusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupModelUsageUpdate) check() error {
	if v, ok := _u.mutation.RuleKey(); ok {
		if err := usergroupmodelusage.RuleKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_key", err: fmt.Errorf(`ent: validator failed for field "UserGroupModelUsage.rule_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserGroupModelUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupmodelusage.Table, usergroupmodelusage.Columns, sqlgraph.NewFieldSpec(usergroupmodelusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupmodelusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupmodelusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupmodelusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupmodelusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupmodelusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuleKey(); ok {
		_spec.SetField(usergroupmodelusage.FieldRuleKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldMonthlyWindowStart, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupmodelusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGroupModelUsageUpdateOne is the builder for updating a single UserGroupModelUsage entity.
type UserGroupModelUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupModelUsageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupModelUsageUpdateOne) SetUpdatedAt(v time.Time) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupModelUsageUpdateOne) SetDeletedAt(v time.Time) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableDeletedAt(v *time.Time) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupModelUsageUpdateOne) ClearDeletedAt() *UserGroupModelUsageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupModelUsageUpdateOne) SetUserID(v int64) *UserGroupModelUsageUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableUserID(v *int64) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupModelUsageUpdateOne) AddUserID(v int64) *UserGroupModelUsageUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupModelUsageUpdateOne) SetGroupID(v int64) *UserGroupModelUsageUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableGroupID(v *int64) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupModelUsageUpdateOne) AddGroupID(v int64) *UserGroupModelUsageUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRuleKey sets the "rule_key" field.
func (_u *UserGroupModelUsageUpdateOne) SetRuleKey(v string) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetRuleKey(v)
	return _u
}

// SetNillableRuleKey sets the "rule_key" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableRuleKey(v *string) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetRuleKey(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) SetDailyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableDailyUsageUsd(v *float64) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) AddDailyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) AddWeeklyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserGroupModelUsageUpdateOne) AddMonthlyUsageUsd(v float64) *UserGroupModelUsageUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) SetDailyWindowStart(v time.Time) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableDailyWindowStart(v *time.Time) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) ClearDailyWindowStart() *UserGroupModelUsageUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) ClearWeeklyWindowStart() *UserGroupModelUsageUpdateOne {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserGroupModelUsageUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupModelUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserGroupModelUsageUpdateOne) ClearMonthlyWindowStart() *UserGroupModelUsageUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// Mutation returns the UserGroupModelUsageMutation object of the builder.
func (_u *UserGroupModelUsageUpdateOne) Mutation() *UserGroupModelUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserGroupModelUsageUpdate builder.
func (_u *UserGroupModelUsageUpdateOne) Where(ps ...predicate.UserGroupModelUsage) *UserGroupModelUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGroupModelUsageUpdateOne) Select(field string, fields ...string) *UserGroupModelUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGroupModelUsage entity.
func (_u *UserGroupModelUsageUpdateOne) Save(ctx context.Context) (*UserGroupModelUsage, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupModelUsageUpdateOne) SaveX(ctx context.Context) *UserGroupModelUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGroupModelUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupModelUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupModelUsageUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupmodelusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupmodelusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupmodelusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupModelUsageUpdateOne) check() error {
	if v, ok := _u.mutation.RuleKey(); ok {
		if err := usergroupmodelusage.RuleKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_key", err: fmt.Errorf(`ent: validator failed for field "UserGroupModelUsage.rule_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserGroupModelUsageUpdateOne) sqlSave(ctx context.Context) (_node *UserGroupModelUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupmodelusage.Table, usergroupmodelusage.Columns, sqlgraph.NewFieldSpec(usergroupmodelusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroupModelUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroupmodelusage.FieldID)
		for _, f := range fields {
			if !usergroupmodelusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroupmodelusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupmodelusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupmodelusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupmodelusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupmodelusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupmodelusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuleKey(); ok {
		_spec.SetField(usergroupmodelusage.FieldRuleKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usergroupmodelusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usergroupmodelusage.FieldMonthlyWindowStart, field.TypeTime)
	}
	_node = &UserGroupModelUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupmodelusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
