// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usergroupmodelusage"
)

// UserGroupModelUsage is the model entity for the UserGroupModelUsage schema.
type UserGroupModelUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// 命中的配额规则原文（归一后小写），非具体模型名
	RuleKey string `json:"rule_key,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// WeeklyUsageUsd holds the value of the "weekly_usage_usd" field.
	WeeklyUsageUsd float64 `json:"weekly_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// DailyWindowStart holds the value of the "daily_window_start" field.
	DailyWindowStart *time.Time `json:"daily_window_start,omitempty"`
	// WeeklyWindowStart holds the value of the "weekly_window_start" field.
	WeeklyWindowStart *time.Time `json:"weekly_window_start,omitempty"`
	// MonthlyWindowStart holds the value of the "monthly_window_start" field.
	MonthlyWindowStart *time.Time `json:"monthly_window_start,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserGroupModelUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usergroupmodelusage.FieldDailyUsageUsd, usergroupmodelusage.FieldWeeklyUsageUsd, usergroupmodelusage.FieldMonthlyUsageUsd:
			values[i] = new(sql.NullFloat64)
		case usergroupmodelusage.FieldID, usergroupmodelusage.FieldUserID, usergroupmodelusage.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case usergroupmodelusage.FieldRuleKey:
			values[i] = new(sql.NullString)
		case usergroupmodelusage.FieldCreatedAt, usergroupmodelusage.FieldUpdatedAt, usergroupmodelusage.FieldDeletedAt, usergroupmodelusage.FieldDailyWindowStart, usergroupmodelusage.FieldWeeklyWindowStart, usergroupmodelusage.FieldMonthlyWindowStart:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserGroupModelUsage fields.
func (_m *UserGroupModelUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usergroupmodelusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usergroupmodelusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usergroupmodelusage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usergroupmodelusage.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case usergroupmodelusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usergroupmodelusage.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case usergroupmodelusage.FieldRuleKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_key", values[i])
			} else if value.Valid {
				_m.RuleKey = value.String
			}
		case usergroupmodelusage.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
			} else if value.Valid {
				_m.DailyUsageUsd = value.Float64
			}
		case usergroupmodelusage.FieldWeeklyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_usage_usd", values[i])
			} else if value.Valid {
				_m.WeeklyUsageUsd = value.Float64
			}
		case usergroupmodelusage.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		case usergroupmodelusage.FieldDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window_start", values[i])
			} else if value.Valid {
				_m.DailyWindowStart = new(time.Time)
				*_m.DailyWindowStart = value.Time
			}
		case usergroupmodelusage.FieldWeeklyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_window_start", values[i])
			} else if value.Valid {
				_m.WeeklyWindowStart = new(time.Time)
				*_m.WeeklyWindowStart = value.Time
			}
		case usergroupmodelusage.FieldMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window_start", values[i])
			} else if value.Valid {
				_m.MonthlyWindowStart = new(time.Time)
				*_m.MonthlyWindowStart = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserGroupModelUsage.
// This includes values selected through modifiers, order, etc.
func (_m *UserGroupModelUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserGroupModelUsage.
// Note that you need to call UserGroupModelUsage.Unwrap() before calling this method if this UserGroupModelUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserGroupModelUsage) Update() *UserGroupModelUsageUpdateOne {
	return NewUserGroupModelUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserGroupModelUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserGroupModelUsage) Unwrap() *UserGroupModelUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserGroupModelUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserGroupModelUsage) String() string {
	var builder strings.Builder
	builder.WriteString("UserGroupModelUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("rule_key=")
	builder.WriteString(_m.RuleKey)
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	if v := _m.DailyWindowStart; v != nil {
		builder.WriteString("daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyWindowStart; v != nil {
		builder.WriteString("weekly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyWindowStart; v != nil {
		builder.WriteString("monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserGroupModelUsages is a parsable slice of UserGroupModelUsage.
type UserGroupModelUsages []*UserGroupModelUsage
