// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usergroupmodelusage"
)

// UserGroupModelUsageCreate is the builder for creating a UserGroupModelUsage entity.
type UserGroupModelUsageCreate struct {
	config
	mutation *UserGroupModelUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserGroupModelUsageCreate) SetCreatedAt(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableCreatedAt(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserGroupModelUsageCreate) SetUpdatedAt(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableUpdatedAt(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserGroupModelUsageCreate) SetDeletedAt(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableDeletedAt(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserGroupModelUsageCreate) SetUserID(v int64) *UserGroupModelUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserGroupModelUsageCreate) SetGroupID(v int64) *UserGroupModelUsageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRuleKey sets the "rule_key" field.
func (_c *UserGroupModelUsageCreate) SetRuleKey(v string) *UserGroupModelUsageCreate {
	_c.mutation.SetRuleKey(v)
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *UserGroupModelUsageCreate) SetDailyUsageUsd(v float64) *UserGroupModelUsageCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableDailyUsageUsd(v *float64) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *UserGroupModelUsageCreate) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableWeeklyUsageUsd(v *float64) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *UserGroupModelUsageCreate) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableMonthlyUsageUsd(v *float64) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *UserGroupModelUsageCreate) SetDailyWindowStart(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableDailyWindowStart(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *UserGroupModelUsageCreate) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *UserGroupModelUsageCreate) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *UserGroupModelUsageCreate) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupModelUsageCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// Mutation returns the UserGroupModelUsageMutation object of the builder.
func (_c *UserGroupModelUsageCreate) Mutation() *UserGroupModelUsageMutation {
	return _c.mutation
}

// Save creates the UserGroupModelUsage in the database.
func (_c *UserGroupModelUsageCreate) Save(ctx context.Context) (*UserGroupModelUsage, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserGroupModelUsageCreate) SaveX(ctx context.Context) *UserGroupModelUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupModelUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupModelUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserGroupModelUsageCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usergroupmodelusage.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupmodelusage.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupmodelusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usergroupmodelusage.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupmodelusage.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupmodelusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := usergroupmodelusage.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := usergroupmodelusage.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := usergroupmodelusage.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserGroupModelUsageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserGroupModelUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserGroupModelUsage.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserGroupModelUsage.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserGroupModelUsage.group_id"`)}
	}
	if _, ok := _c.mutation.RuleKey(); !ok {
		return &ValidationError{Name: "rule_key", err: errors.New(`ent: missing required field "UserGroupModelUsage.rule_key"`)}
	}
	if v, ok := _c.mutation.RuleKey(); ok {
		if err := usergroupmodelusage.RuleKeyValidator(v); err != nil {
			return &ValidationError{Name: "rule_key", err: fmt.Errorf(`ent: validator failed for field "UserGroupModelUsage.rule_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "UserGroupModelUsage.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "UserGroupModelUsage.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "UserGroupModelUsage.monthly_usage_usd"`)}
	}
	return nil
}

func (_c *UserGroupModelUsageCreate) sqlSave(ctx context.Context) (*UserGroupModelUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserGroupModelUsageCreate) createSpec() (*UserGroupModelUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGroupModelUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usergroupmodelusage.Table, sqlgraph.NewFieldSpec(usergroupmodelusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupmodelusage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usergroupmodelusage.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usergroupmodelusage.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.RuleKey(); ok {
		_spec.SetField(usergroupmodelusage.FieldRuleKey, field.TypeString, value)
		_node.RuleKey = value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupmodelusage.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupModelUsage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupModelUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupModelUsageCreate) OnConflict(opts ...sql.ConflictOption) *UserGroupModelUsageUpsertOne {
	_c.conflict = opts
	return &UserGroupModelUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupModelUsageCreate) OnConflictColumns(columns ...string) *UserGroupModelUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupModelUsageUpsertOne{
		create: _c,
	}
}

type (
	// UserGroupModelUsageUpsertOne is the builder for "upsert"-ing
	//  one UserGroupModelUsage node.
	UserGroupModelUsageUpsertOne struct {
		create *UserGroupModelUsageCreate
	}

	// UserGroupModelUsageUpsert is the "OnConflict" setter.
	UserGroupModelUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupModelUsageUpsert) SetUpdatedAt(v time.Time) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateUpdatedAt() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupModelUsageUpsert) SetDeletedAt(v time.Time) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateDeletedAt() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupModelUsageUpsert) ClearDeletedAt() *UserGroupModelUsageUpsert {
	u.SetNull(usergroupmodelusage.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGroupModelUsageUpsert) SetUserID(v int64) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateUserID() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupModelUsageUpsert) AddUserID(v int64) *UserGroupModelUsageUpsert {
	u.Add(usergroupmodelusage.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupModelUsageUpsert) SetGroupID(v int64) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateGroupID() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupModelUsageUpsert) AddGroupID(v int64) *UserGroupModelUsageUpsert {
	u.Add(usergroupmodelusage.FieldGroupID, v)
	return u
}

// SetRuleKey sets the "rule_key" field.
func (u *UserGroupModelUsageUpsert) SetRuleKey(v string) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldRuleKey, v)
	return u
}

// UpdateRuleKey sets the "rule_key" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateRuleKey() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldRuleKey)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsert) SetDailyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateDailyUsageUsd() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsert) AddDailyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Add(usergroupmodelusage.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsert) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateWeeklyUsageUsd() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsert) AddWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Add(usergroupmodelusage.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsert) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateMonthlyUsageUsd() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsert) AddMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsert {
	u.Add(usergroupmodelusage.FieldMonthlyUsageUsd, v)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupModelUsageUpsert) SetDailyWindowStart(v time.Time) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateDailyWindowStart() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupModelUsageUpsert) ClearDailyWindowStart() *UserGroupModelUsageUpsert {
	u.SetNull(usergroupmodelusage.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsert) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateWeeklyWindowStart() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsert) ClearWeeklyWindowStart() *UserGroupModelUsageUpsert {
	u.SetNull(usergroupmodelusage.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsert) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageUpsert {
	u.Set(usergroupmodelusage.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsert) UpdateMonthlyWindowStart() *UserGroupModelUsageUpsert {
	u.SetExcluded(usergroupmodelusage.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsert) ClearMonthlyWindowStart() *UserGroupModelUsageUpsert {
	u.SetNull(usergroupmodelusage.FieldMonthlyWindowStart)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupModelUsageUpsertOne) UpdateNewValues() *UserGroupModelUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usergroupmodelusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserGroupModelUsageUpsertOne) Ignore() *UserGroupModelUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupModelUsageUpsertOne) DoNothing() *UserGroupModelUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupModelUsageCreate.OnConflict
// documentation for more info.
func (u *UserGroupModelUsageUpsertOne) Update(set func(*UserGroupModelUsageUpsert)) *UserGroupModelUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupModelUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupModelUsageUpsertOne) SetUpdatedAt(v time.Time) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateUpdatedAt() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupModelUsageUpsertOne) SetDeletedAt(v time.Time) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateDeletedAt() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupModelUsageUpsertOne) ClearDeletedAt() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupModelUsageUpsertOne) SetUserID(v int64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupModelUsageUpsertOne) AddUserID(v int64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateUserID() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupModelUsageUpsertOne) SetGroupID(v int64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupModelUsageUpsertOne) AddGroupID(v int64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateGroupID() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetRuleKey sets the "rule_key" field.
func (u *UserGroupModelUsageUpsertOne) SetRuleKey(v string) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetRuleKey(v)
	})
}

// UpdateRuleKey sets the "rule_key" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateRuleKey() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateRuleKey()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) SetDailyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) AddDailyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateDailyUsageUsd() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) AddWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateWeeklyUsageUsd() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsertOne) AddMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateMonthlyUsageUsd() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupModelUsageUpsertOne) SetDailyWindowStart(v time.Time) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateDailyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupModelUsageUpsertOne) ClearDailyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsertOne) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateWeeklyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsertOne) ClearWeeklyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsertOne) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertOne) UpdateMonthlyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsertOne) ClearMonthlyWindowStart() *UserGroupModelUsageUpsertOne {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *UserGroupModelUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupModelUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupModelUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserGroupModelUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserGroupModelUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserGroupModelUsageCreateBulk is the builder for creating many UserGroupModelUsage entities in bulk.
type UserGroupModelUsageCreateBulk struct {
	config
	err      error
	builders []*UserGroupModelUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the UserGroupModelUsage entities in the database.
func (_c *UserGroupModelUsageCreateBulk) Save(ctx context.Context) ([]*UserGroupModelUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserGroupModelUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGroupModelUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserGroupModelUsageCreateBulk) SaveX(ctx context.Context) []*UserGroupModelUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupModelUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupModelUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupModelUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupModelUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupModelUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserGroupModelUsageUpsertBulk {
	_c.conflict = opts
	return &UserGroupModelUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupModelUsageCreateBulk) OnConflictColumns(columns ...string) *UserGroupModelUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupModelUsageUpsertBulk{
		create: _c,
	}
}

// UserGroupModelUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of UserGroupModelUsage nodes.
type UserGroupModelUsageUpsertBulk struct {
	create *UserGroupModelUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupModelUsageUpsertBulk) UpdateNewValues() *UserGroupModelUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usergroupmodelusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupModelUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserGroupModelUsageUpsertBulk) Ignore() *UserGroupModelUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupModelUsageUpsertBulk) DoNothing() *UserGroupModelUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupModelUsageCreateBulk.OnConflict
// documentation for more info.
func (u *UserGroupModelUsageUpsertBulk) Update(set func(*UserGroupModelUsageUpsert)) *UserGroupModelUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupModelUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupModelUsageUpsertBulk) SetUpdatedAt(v time.Time) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateUpdatedAt() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupModelUsageUpsertBulk) SetDeletedAt(v time.Time) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateDeletedAt() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupModelUsageUpsertBulk) ClearDeletedAt() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupModelUsageUpsertBulk) SetUserID(v int64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupModelUsageUpsertBulk) AddUserID(v int64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateUserID() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupModelUsageUpsertBulk) SetGroupID(v int64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupModelUsageUpsertBulk) AddGroupID(v int64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateGroupID() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetRuleKey sets the "rule_key" field.
func (u *UserGroupModelUsageUpsertBulk) SetRuleKey(v string) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetRuleKey(v)
	})
}

// UpdateRuleKey sets the "rule_key" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateRuleKey() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateRuleKey()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) SetDailyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) AddDailyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateDailyUsageUsd() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) SetWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) AddWeeklyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateWeeklyUsageUsd() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) SetMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupModelUsageUpsertBulk) AddMonthlyUsageUsd(v float64) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateMonthlyUsageUsd() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) SetDailyWindowStart(v time.Time) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateDailyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) ClearDailyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) SetWeeklyWindowStart(v time.Time) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateWeeklyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) ClearWeeklyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) SetMonthlyWindowStart(v time.Time) *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupModelUsageUpsertBulk) UpdateMonthlyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupModelUsageUpsertBulk) ClearMonthlyWindowStart() *UserGroupModelUsageUpsertBulk {
	return u.Update(func(s *UserGroupModelUsageUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *UserGroupModelUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserGroupModelUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupModelUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupModelUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
