// Code generated by ent, DO NOT EDIT.

package usergroupmodelusage

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usergroupmodelusage type in the database.
	Label = "user_group_model_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRuleKey holds the string denoting the rule_key field in the database.
	FieldRuleKey = "rule_key"
	// FieldDailyUsageUsd holds the string denoting the daily_usage_usd field in the database.
	FieldDailyUsageUsd = "daily_usage_usd"
	// FieldWeeklyUsageUsd holds the string denoting the weekly_usage_usd field in the database.
	FieldWeeklyUsageUsd = "weekly_usage_usd"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// FieldDailyWindowStart holds the string denoting the daily_window_start field in the database.
	FieldDailyWindowStart = "daily_window_start"
	// FieldWeeklyWindowStart holds the string denoting the weekly_window_start field in the database.
	FieldWeeklyWindowStart = "weekly_window_start"
	// FieldMonthlyWindowStart holds the string denoting the monthly_window_start field in the database.
	FieldMonthlyWindowStart = "monthly_window_start"
	// Table holds the table name of the usergroupmodelusage in the database.
	Table = "user_group_model_usage"
)

// Columns holds all SQL columns for usergroupmodelusage fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldGroupID,
	FieldRuleKey,
	FieldDailyUsageUsd,
	FieldWeeklyUsageUsd,
	FieldMonthlyUsageUsd,
	FieldDailyWindowStart,
	FieldWeeklyWindowStart,
	FieldMonthlyWindowStart,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RuleKeyValidator is a validator for the "rule_key" field. It is called by the builders before save.
	RuleKeyValidator func(string) error
	// DefaultDailyUsageUsd holds the default value on creation for the "daily_usage_usd" field.
	DefaultDailyUsageUsd float64
	// DefaultWeeklyUsageUsd holds the default value on creation for the "weekly_usage_usd" field.
	DefaultWeeklyUsageUsd float64
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd float64
)

// OrderOption defines the ordering options for the UserGroupModelUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRuleKey orders the results by the rule_key field.
func ByRuleKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleKey, opts...).ToFunc()
}

// ByDailyUsageUsd orders the results by the daily_usage_usd field.
func ByDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageUsd, opts...).ToFunc()
}

// ByWeeklyUsageUsd orders the results by the weekly_usage_usd field.
func ByWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyUsageUsd, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// ByDailyWindowStart orders the results by the daily_window_start field.
func ByDailyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyWindowStart, opts...).ToFunc()
}

// ByWeeklyWindowStart orders the results by the weekly_window_start field.
func ByWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyWindowStart, opts...).ToFunc()
}

// ByMonthlyWindowStart orders the results by the monthly_window_start field.
func ByMonthlyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyWindowStart, opts...).ToFunc()
}
