// Code generated by ent, DO NOT EDIT.

package usergroupmodelusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldGroupID, v))
}

// RuleKey applies equality check predicate on the "rule_key" field. It's identical to RuleKeyEQ.
func RuleKey(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldRuleKey, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsd applies equality check predicate on the "weekly_usage_usd" field. It's identical to WeeklyUsageUsdEQ.
func WeeklyUsageUsd(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// DailyWindowStart applies equality check predicate on the "daily_window_start" field. It's identical to DailyWindowStartEQ.
func DailyWindowStart(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDailyWindowStart, v))
}

// WeeklyWindowStart applies equality check predicate on the "weekly_window_start" field. It's identical to WeeklyWindowStartEQ.
func WeeklyWindowStart(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// MonthlyWindowStart applies equality check predicate on the "monthly_window_start" field. It's identical to MonthlyWindowStartEQ.
func MonthlyWindowStart(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldGroupID, v))
}

// RuleKeyEQ applies the EQ predicate on the "rule_key" field.
func RuleKeyEQ(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldRuleKey, v))
}

// RuleKeyNEQ applies the NEQ predicate on the "rule_key" field.
func RuleKeyNEQ(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldRuleKey, v))
}

// RuleKeyIn applies the In predicate on the "rule_key" field.
func RuleKeyIn(vs ...string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldRuleKey, vs...))
}

// RuleKeyNotIn applies the NotIn predicate on the "rule_key" field.
func RuleKeyNotIn(vs ...string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldRuleKey, vs...))
}

// RuleKeyGT applies the GT predicate on the "rule_key" field.
func RuleKeyGT(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldRuleKey, v))
}

// RuleKeyGTE applies the GTE predicate on the "rule_key" field.
func RuleKeyGTE(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldRuleKey, v))
}

// RuleKeyLT applies the LT predicate on the "rule_key" field.
func RuleKeyLT(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldRuleKey, v))
}

// RuleKeyLTE applies the LTE predicate on the "rule_key" field.
func RuleKeyLTE(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldRuleKey, v))
}

// RuleKeyContains applies the Contains predicate on the "rule_key" field.
func RuleKeyContains(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldContains(FieldRuleKey, v))
}

// RuleKeyHasPrefix applies the HasPrefix predicate on the "rule_key" field.
func RuleKeyHasPrefix(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldHasPrefix(FieldRuleKey, v))
}

// RuleKeyHasSuffix applies the HasSuffix predicate on the "rule_key" field.
func RuleKeyHasSuffix(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldHasSuffix(FieldRuleKey, v))
}

// RuleKeyEqualFold applies the EqualFold predicate on the "rule_key" field.
func RuleKeyEqualFold(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEqualFold(FieldRuleKey, v))
}

// RuleKeyContainsFold applies the ContainsFold predicate on the "rule_key" field.
func RuleKeyContainsFold(v string) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldContainsFold(FieldRuleKey, v))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsdEQ applies the EQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdNEQ applies the NEQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdIn applies the In predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdNotIn applies the NotIn predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNotIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdGT applies the GT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdGTE applies the GTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLT applies the LT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLTE applies the LTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// DailyWindowStartEQ applies the EQ predicate on the "daily_window_start" field.
func DailyWindowStartEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartNEQ applies the NEQ predicate on the "daily_window_start" field.
func DailyWindowStartNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartIn applies the In predicate on the "daily_window_start" field.
func DailyWindowStartIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartNotIn applies the NotIn predicate on the "daily_window_start" field.
func DailyWindowStartNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartGT applies the GT predicate on the "daily_window_start" field.
func DailyWindowStartGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldDailyWindowStart, v))
}

// DailyWindowStartGTE applies the GTE predicate on the "daily_window_start" field.
func DailyWindowStartGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldDailyWindowStart, v))
}

// DailyWindowStartLT applies the LT predicate on the "daily_window_start" field.
func DailyWindowStartLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldDailyWindowStart, v))
}

// DailyWindowStartLTE applies the LTE predicate on the "daily_window_start" field.
func DailyWindowStartLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldDailyWindowStart, v))
}

// DailyWindowStartIsNil applies the IsNil predicate on the "daily_window_start" field.
func DailyWindowStartIsNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIsNull(FieldDailyWindowStart))
}

// DailyWindowStartNotNil applies the NotNil predicate on the "daily_window_start" field.
func DailyWindowStartNotNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotNull(FieldDailyWindowStart))
}

// WeeklyWindowStartEQ applies the EQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartNEQ applies the NEQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIn applies the In predicate on the "weekly_window_start" field.
func WeeklyWindowStartIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartNotIn applies the NotIn predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartGT applies the GT predicate on the "weekly_window_start" field.
func WeeklyWindowStartGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartGTE applies the GTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLT applies the LT predicate on the "weekly_window_start" field.
func WeeklyWindowStartLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLTE applies the LTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIsNil applies the IsNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartIsNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIsNull(FieldWeeklyWindowStart))
}

// WeeklyWindowStartNotNil applies the NotNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotNull(FieldWeeklyWindowStart))
}

// MonthlyWindowStartEQ applies the EQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartNEQ applies the NEQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartNEQ(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIn applies the In predicate on the "monthly_window_start" field.
func MonthlyWindowStartIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartNotIn applies the NotIn predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotIn(vs ...time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartGT applies the GT predicate on the "monthly_window_start" field.
func MonthlyWindowStartGT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartGTE applies the GTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartGTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldGTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLT applies the LT predicate on the "monthly_window_start" field.
func MonthlyWindowStartLT(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLTE applies the LTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartLTE(v time.Time) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldLTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIsNil applies the IsNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartIsNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldIsNull(FieldMonthlyWindowStart))
}

// MonthlyWindowStartNotNil applies the NotNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotNil() predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.FieldNotNull(FieldMonthlyWindowStart))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGroupModelUsage) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGroupModelUsage) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGroupModelUsage) predicate.UserGroupModelUsage {
	return predicate.UserGroupModelUsage(sql.NotPredicates(p))
}
